-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.2.6-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for control
CREATE DATABASE IF NOT EXISTS `control` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `control`;

-- Dumping structure for table control.task_run
CREATE TABLE IF NOT EXISTS `task_run` (
  `taskkey` int(11) NOT NULL AUTO_INCREMENT,
  `taskid` int(11) DEFAULT NULL,
  `taskgroupid` int(11) DEFAULT 1,
  `taskname` varchar(50) DEFAULT NULL,
  `taskbody` varchar(4000) DEFAULT NULL,
  `taskdescription` varchar(50) DEFAULT NULL,
  `tasktype` int(11) NOT NULL DEFAULT 11,
  `taskactiveflag` int(11) DEFAULT 0,
  `taskstatusflag` int(11) DEFAULT 0,
  `taskmodifieddate` datetime DEFAULT NULL,
  `taskcreationdate` datetime DEFAULT NULL,
  `tjob` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`taskkey`)
) ENGINE=InnoDB AUTO_INCREMENT=79 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- Dumping data for table control.task_run: ~70 rows (approximately)
/*!40000 ALTER TABLE `task_run` DISABLE KEYS */;
INSERT INTO `task_run` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`, `tjob`) VALUES
	(1, 1, 1, 'truncate barrier_landing.ps_mapping_eis', 'truncate table barrier_landing.ps_mapping_eis;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_ps_mapping_eis'),
	(2, 2, 1, 'truncate barrier_landing.ps_mapping_nm01', 'truncate table barrier_landing.ps_mapping_nm01;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_ps_mapping_nm01'),
	(3, 3, 1, 'truncate  barrier_landing.work_order_eis_map1', 'truncate table barrier_landing.work_order_eis_map1;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_eis_map1'),
	(4, 4, 1, 'truncate barrier_landing.work_order_eis_mcp1', 'truncate table barrier_landing.work_order_eis_mcp1;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_eis_mcp1'),
	(5, 5, 1, 'truncate barrier_landing.work_order_eis_mdp1', 'truncate table barrier_landing.work_order_eis_mdp1;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_eis_mdp1'),
	(6, 6, 1, 'truncate  barrier_landing.work_order_nm01_chis', 'truncate table barrier_landing.work_order_nm01_chis;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_chis'),
	(7, 7, 1, 'truncate  barrier_landing.work_order_nm01_f3fa', 'truncate table barrier_landing.work_order_nm01_f3fa;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_f3fa'),
	(8, 8, 1, 'truncate barrier_landing.work_order_nm01_grov', 'truncate table barrier_landing.work_order_nm01_grov;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_grov'),
	(9, 9, 1, 'truncate barrier_landing.work_order_nm01_grow', 'truncate table barrier_landing.work_order_nm01_grow;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_grow'),
	(10, 10, 1, 'truncate  barrier_landing.work_order_nm01_mj6a', 'truncate table barrier_landing.work_order_nm01_mj6a;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_mj6a'),
	(11, 11, 1, 'truncate  barrier_landing.work_order_nm01_mkew', 'truncate table barrier_landing.work_order_nm01_mkew;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_mkew'),
	(12, 12, 1, 'truncate  barrier_landing.work_order_nm01_mst1', 'truncate table barrier_landing.work_order_nm01_mst1;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_mst1'),
	(13, 13, 1, 'truncate barrier_landing.work_order_nm01_stam', 'truncate table barrier_landing.work_order_nm01_stam;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_stam'),
	(14, 14, 1, 'truncate  barrier_landing.work_order_nm01_wind', 'truncate table barrier_landing.work_order_nm01_wind;', NULL, 11, 0, 0, '2017-10-02 12:52:05', '2017-10-02 12:52:05', 'jb_land_work_order_nm01_wind'),
	(19, 19, 4, 'Load barrier_landing.work_order_eis_mcp1', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_eis_mcp1.txt\' REPLACE INTO TABLE `barrier_landing`.`work_order_eis_mcp1` CHARACTER SET latin1 FIELDS TERMINATED BY \'	\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`functional_loc`, `description`, `order_type`, `Order`, `maint_activ_type`, `description_4`, `planner_group`, `main_work_ctr`, `user_status`, `system_status`, `Priority`, `estimated_costs`, `total_act_costs`, `total_settlemt`, `total_plnnd_costs`, `tot_sum_plan`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `available_from30`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `subnet_work_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, country`, `device_data`, `sort_field`, `description_50`, `equipment`, `created_on`, `entered_by`, `billingform`, `actual_release`, `actual_finish`, `actual_finish1`, `basic_fin_date`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `bas_start_date`, `sched_start`, `actual_start1`, `start_time`, `sched_start_time`, `hist_fr`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_Area`, `cost_center`, `resp_cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_81`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority_95`, `wbs_element`, `wbs_ord_header`, `notification`, `region`, `revision`, `serial_number`, `material`, `service_product`, `service_product_104`, `division`, `division_sales` ,`location` , `street` ,`maint_plant` ,`telephone` ,`sales_office` ,`sales_group` ,`sales_org` ,`sales_org_sales` ,`superior_act` ,`distr_channel` ,`distr_channel_sal` ,`currency` ,`maint_item` ,`maintenance_plan` ,`plant` ,`comp` ,`overhead_key` ,`earlst_allow_fin_dat` ,`earl_allow_start_dat` ,`latest_allow_fin_dat` ,`original_due_date` ,`object_list` ,`catalog_type` ,`code_group` ,`coding`);', NULL, 12, 1, 1, '2017-10-02 14:55:27', '2017-10-02 14:55:27', 'jb_land_work_order_eis_mcp1'),
	(20, 20, 4, 'Load barrier_landing.work_order_nm01_wind', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_wind.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_wind` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`,`division_sales`,`location`,`street` ,`maint_plant` , `telephone` ,`estimated_costs` ,`sales_office` ,`sales_group` , `sales_org` ,`sales_org  - Sales` ,`superior_act` ,`distr_channel` ,`distr_Channel_sa_l` ,`currency` ,`maint_item` , `maintenance_plan` , `plant` , `comp` ,`overhead_key` ,`earlst_allow_fin_dat` , `earl_allow_start_dat` , `latest_allow_fin_dat` ,`original_due_date` ,`bas_start_date` ,`user_status` ,`system_status` ,`order_type` ,`revision` , `basic_fin_date` );', NULL, 12, 1, 1, '2017-10-02 15:04:50', '2017-10-02 15:04:50', 'jb_land_work_order_nm01_wind'),
	(21, 21, 4, 'Load barrier_landing.work_order_nm01_stam', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_stam.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_stam` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales`,`location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`, `currency`, `maint_item`,`maintenance_plan`,`plant`, `comp`,`overhead_key`,`earlst_allow_fin_dat`, `earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`, `user_status`,`system_status`,`order_type`, `revision`,`basic_fin_date`);', NULL, 12, 1, 1, '2017-10-02 15:04:55', '2017-10-02 15:04:55', 'jb_land_work_order_nm01_stam'),
	(22, 22, 4, 'Load barrier_landing.work_order_nm01_mst1', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_mst1.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_mst1` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales, `location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`,`user_status`,`system_status`,`order_type`,`revision`,`basic_fin_date`);\r\n', NULL, 12, 1, 1, '2017-10-02 15:04:57', '2017-10-02 15:04:57', 'jb_land_work_order_nm01_mst1'),
	(23, 23, 4, 'Load barrier_landing.work_order_nm01_mkew', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_mkew.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_mkew` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales`,`location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`, `currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`,`user_status`,`system_status`,`order_type`,`revision`,`basic_fin_date`); ', NULL, 12, 1, 1, '2017-10-02 15:04:59', '2017-10-02 15:04:59', 'jb_land_work_order_nm01_mkew'),
	(24, 24, 4, 'Load barrier_landing.work_order_nm01_mj6a', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_mj6a.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_mj6a` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales`, `location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`,`user_status`,`system_status`,`order_type`,`revision`,`basic_fin_date`);', NULL, 12, 1, 1, '2017-10-02 15:05:00', '2017-10-02 15:05:00', 'jb_land_work_order_nm01_mj6a'),
	(25, 25, 4, 'Load barrier_landing.work_order_nm01_grow', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_grow.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_grow` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`,`division`,`division_sales`,`location` ,`street` ,`maint_plant` ,`telephone` ,`estimated_costs` ,`sales_office` ,`sales_group` ,`sales_org` ,`sales_org  - Sales` ,`superior_act` ,`distr_channel` ,`distr_Channel_sa_l` ,`currency` ,`maint_item` ,`maintenance_plan` ,`plant` ,`comp` ,`overhead_key` ,`earlst_allow_fin_dat` ,`earl_allow_start_dat` ,`latest_allow_fin_dat` ,`original_due_date` ,`bas_start_date` , `user_status` ,`system_status` ,`order_type` ,`revision` ,`basic_fin_date`); ', NULL, 12, 1, 1, '2017-10-02 15:05:02', '2017-10-02 15:05:02', 'jb_land_work_order_nm01_grow'),
	(26, 26, 4, 'Load barrier_landing.work_order_nm01_grov', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_grov.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_grov` FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales`,`location`,`street`, `maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`, `original_due_date`,`bas_start_date`,`user_status`,`system_status`,`order_type`,`revision`,`basic_fin_date`);', NULL, 12, 1, 1, '2017-10-02 15:05:04', '2017-10-02 15:05:04', 'jb_land_work_order_nm01_grov'),
	(27, 27, 4, 'Load barrier_landing.work_order_nm01_f3fa', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_f3fa.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_f3fa` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `user_status`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`,`division`,`division_sales`,`location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`,`system_status`,`order_type`,`revision`,`basic_fin_date`);', NULL, 12, 1, 1, '2017-10-02 15:05:05', '2017-10-02 15:05:05', 'jb_land_work_order_nm01_f3fa'),
	(28, 28, 4, 'Load barrier_landing.work_order_nm01_chis', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_chis.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_chis` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`bas_start_date`, `order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `user_status`, `system_status`, `order_type`, `revision`, `basic_fin_date`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`,`serial_number` ,`material` ,`service_product` ,`service_product_1` ,`division` ,`division_sales` ,`location` ,`street` ,`maint_plant` ,`telephone` ,`estimated_costs` ,`sales_office` ,`sales_group` ,`sales_org` ,`sales_org  - Sales` ,`superior_act` ,`distr_channel` ,`distr_Channel_sa_l` ,`currency` ,`maint_item` ,`maintenance_plan` ,`plant` ,`comp` ,`overhead_key` ,`earlst_allow_fin_dat`,`earl_allow_start_dat` ,`latest_allow_fin_dat` ,`original_due_date`);', NULL, 12, 1, 1, '2017-10-02 15:05:07', '2017-10-02 15:05:07', 'jb_land_work_order_nm01_chis'),
	(29, 29, 4, 'Load barrier_landing.work_order_eis_mdp1', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_eis_mdp1.txt\' REPLACE INTO TABLE `barrier_landing`.`work_order_eis_mdp1` CHARACTER SET latin1 FIELDS TERMINATED BY \'	\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`functional_loc`, `description`, `order_type`, `Order`, `maint_activ_type`, `description_4`, `planner_group`, `main_work_ctr`, `user_status`, `system_status`, `Priority`, `estimated_costs`, `total_act_costs`, `total_settlemt`, `total_plnnd_costs`, `tot_sum_plan`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `available_from30`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `subnet_work_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_50`, `equipment`, `created_on`, `entered_by`, `billingform`, `actual_release`, `actual_finish`, `actual_finish1`, `basic_fin_date`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `bas_start_date`, `sched_start`, `actual_start1`, `start_time`, `sched_start_time`, `hist_fr`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_Area`, `cost_center`, `resp_cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_81`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority_95`, `wbs_element`, `wbs_ord_header`, `notification`, `region`, `revision`, `serial_number`, `material`, `service_product`, `service_product_104`, `division`, `division_sales`,`location`,`street`,`maint_plant`,`telephone`,`sales_office`,`sales_group`,`sales_org`,`sales_org_sales`,`superior_act`,`distr_channel`,`distr_channel_sal`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`object_list`,`catalog_type`,`code_group`,`coding`);\r\n', NULL, 12, 1, 1, '2017-10-02 15:05:08', '2017-10-02 15:05:08', 'jb_land_work_order_eis_mdp1'),
	(30, 30, 4, 'Load barrier_landing.work_order_eis_map1', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_eis_map1.txt\' REPLACE INTO TABLE `barrier_landing`.`work_order_eis_map1` CHARACTER SET latin1 FIELDS TERMINATED BY \'	\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES ( `functional_loc`,`description`,`order_type`,`Order`,`maint_activ_type`,`description_4`,`planner_group`,`main_work_ctr`,`user_status`,`system_status`,`Priority`,`estimated_costs`,`total_act_costs`,`total_settlemt`,`total_plnnd_costs`,`tot_sum_plan`,`total_rev_act`,`tot_plan_rev`,`tot_sum_actual`,`abc_indic`,`reference_date`,`ref_element_pm_ps`,`address_number`,`reference_time`,`changed_on`,`changed_by`,`available_to`,`avail_to_time`,`asset`,`sub_number`,`available_from`,`available_from30`,`system_condition`,`work_center`,`priority_type`,`res_purc_req`,`subnet_work_of`,`order_category`,`plant_wk_cntr`,`assembly`,`assembly_desc`,`plant_section`,`acctg_indicator`,`po_date`,`po_number`,`company_code`,`city`,`district`,`country`,`device_data`,`sort_field`,`description_50`,`equipment`,`created_on`,`entered_by`,`billingform`,`actual_release`,`actual_finish`,`actual_finish1`,`basic_fin_date`,`sched_finish`,`basic_fin_time`,`finish_time`,`business_area`,`actual_start`,`bas_start_date`,`sched_start`,`actual_start1`,`start_time`,`sched_start_time`,`hist_fr`,`planning_plant`,`costing_sheet`,`sales_document`,`item`,`co_Area`,`cost_center`,`resp_cost_cntr`,`customer`,`leading_order`,`deletion_flag`,`long_txt_exists`,`description_81`,`superior_order`,`base_unit`,`quantity`,`room`,`list_name`,`object_number`,`paging_status`,`pgrp_task_list`,`order_plan_ind`,`group_counter`,`group`,`postal_code`,`profit_center`,`priority_95`,`wbs_element`,`wbs_ord_header`,`notification`,`region`,`revision`,`serial_number`,`material`,`service_product`,`service_product_104`,`division`,`division_sales`,`location`,`street`,`maint_plant`,`telephone`,`sales_office`,`sales_group`,`sales_org`,`sales_org_sales`,`superior_act`,`distr_channel`,`distr_channel_sal`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`object_list`,`catalog_type`,`code_group`,`coding`);', NULL, 12, 1, 1, '2017-10-02 15:05:10', '2017-10-02 15:05:10', 'jb_land_work_order_eis_map1'),
	(31, 31, 4, 'Load barrier_landing.ps_mapping_nm01', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'ps_mapping_nm01.csv\' REPLACE INTO TABLE `barrier_landing`.`ps_mapping_nm01` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`floc`, `floc_type`, `description`, `support_floc`, `support_floc_description`, `abc_indicator`, `criticality_justification`, `ps_ref1`, `ps_ref2`, `new_ps_ref_1`, `new_ps_ref_2`, `nl_sce`);', NULL, 12, 1, 1, '2017-10-02 15:05:12', '2017-10-02 15:05:12', 'jb_land_ps_mapping_nm01'),
	(32, 32, 4, 'Load barrier_landing.ps_mapping_eis', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'ps_mapping_eis.csv\' REPLACE INTO TABLE `barrier_landing`.`ps_mapping_eis` FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`floc`, `description`, `system_status`, `user_status`, `support_floc`, `ps_ref_1`, `ps_ref_2`, `ps_ref_3`, `ps_mapping_barrier_1`, `ps_mapping_barrier_2`, `ps_mapping_barrier_3`);', NULL, 12, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_land_ps_mapping_eis'),
	(34, 34, 6, 'jb_abc_indicator_refdt', 'jb_abc_indicator_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_abc_indicator_refdt'),
	(35, 35, 6, 'jb_asset_refdt', 'jb_asset_refdt_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_asset_refdt'),
	(36, 36, 6, 'jb_asset_rule_set_refdt', 'jb_asset_rule_set_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_asset_rule_set_refdt'),
	(37, 37, 6, 'jb_barrier_element_refdt', 'jb_barrier_element_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_barrier_element_refdt'),
	(38, 38, 6, 'jb_barrier_metric_refdt', 'jb_barrier_metric_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_barrier_metric_refdt'),
	(39, 39, 6, 'jb_barrier_type_refdt', 'jb_barrier_type_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_barrier_type_refdt'),
	(40, 40, 6, 'jb_business_unit_refdt', 'jb_business_unit_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_business_unit_refdt'),
	(41, 41, 6, 'jb_facility_refdt', 'jb_facility_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_facility_refdt'),
	(42, 42, 6, 'jb_facility_rule_set_refdt', 'jb_facility_rule_set_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_facility_rule_set_refdt'),
	(43, 43, 6, 'jb_performance_standard_mapping_refdt', 'jb_performance_standard_mapping_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_performance_standard_mapping_refdt'),
	(44, 44, 6, 'jb_performance_standard_refdt', 'jb_performance_standard_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_performance_standard_refdt'),
	(45, 45, 6, 'jb_planner_group_refdt', 'jb_planner_group_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_planner_group_refdt'),
	(46, 46, 6, 'jb_role_refdt', 'jb_role_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_role_refdt'),
	(47, 47, 6, 'jb_user_refdt', 'jb_user_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_user_refdt'),
	(48, 62, 3, 'jb_ods_merge_work_order_eis_map1', 'jb_ods_merge_work_order_eis_map1', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_work_order_eis_map1'),
	(49, 200, 3, 'jb_ods_merge_eis', 'jb_ods_merge_eis', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_eis'),
	(50, 89, 3, 'jb_ods_work_order_eis_mcp1', 'jb_ods_work_order_eis_mcp1', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_work_order_eis_mcp1'),
	(51, 51, 3, 'jb_ods_merge_nm01_chis', 'jb_ods_merge_nm01_chis', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_chis'),
	(52, 52, 3, 'jb_ods_merge_nm01_f3fa', 'jb_ods_merge_nm01_f3fa', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_f3fa'),
	(53, 53, 3, 'jb_ods_merge_nm01_grov', 'jb_ods_merge_nm01_grov', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_grov'),
	(54, 54, 3, 'jb_ods_merge_nm01_grow', 'jb_ods_merge_nm01_grow', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_grow'),
	(55, 55, 3, 'jb_ods_merge_nm01_mj6a', 'jb_ods_merge_nm01_mj6a', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_mj6a'),
	(56, 56, 3, 'jb_ods_merge_nm01_mkew', 'jb_ods_merge_nm01_mkew', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_mkew'),
	(57, 57, 3, 'jb_ods_merge_nm01_mst1', 'jb_ods_merge_nm01_mst1', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_mst1'),
	(58, 58, 3, 'jb_ods_merge_nm01_stam', 'jb_ods_merge_nm01_stam', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_stam'),
	(59, 59, 3, 'jb_ods_merge_nm01_wind', 'jb_ods_merge_nm01_wind', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_wind'),
	(60, 60, 8, 'refresh_sap_work_order_data', 'refresh_sap_work_order_data', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'refresh_sap_work_order_data'),
	(61, 61, 8, 'refresh_facility_level_data', 'refresh_facility_level_data', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'refresh_facility_level_data'),
	(62, 62, 8, 'refresh_asset_level_data', 'refresh_asset_level_data', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'refresh_asset_level_data'),
	(63, 63, 8, 'refresh_work_order_level_data', 'refresh_work_order_level_data', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'refresh_work_order_level_data'),
	(64, 64, 6, 'jb_barrier_refdt', 'jb_barrier_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_barrier_refdt'),
	(65, 65, 5, 'jb_barrier_init_refdt', 'jb_barrier_init_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_barrier_init_refdt'),
	(66, 66, 5, 'jb_business_unit_refdt', 'jb_business_unit_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_business_unit_refdt'),
	(67, 67, 5, 'jb_asset_init_refdt', 'jb_asset_init_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_asset_init_refdt'),
	(68, 68, 5, 'jb_barrier_type_init_refdt', 'jb_barrier_type_init_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_barrier_type_init_refdt'),
	(69, 69, 5, 'jb_abc_indicator_init_refdt', 'jb_abc_indicator_init_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_abc_indicator_init_refdt'),
	(70, 70, 5, 'jb_barrier_metric_init_refdt', 'jb_barrier_metric_init_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_barrier_metric_init_refdt'),
	(71, 71, 5, 'jb_facility_init_refdt', 'jb_facility_init_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_facility_init_refdt'),
	(72, 72, 5, 'jb_performance_standard_init_refdt', 'jb_performance_standard_init_refdt', NULL, 14, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_performance_standard_init_refdt'),
	(75, 100, 3, 'jb_ods_merge_nm01_all', 'jb_ods_merge_nm01_all', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_nm01_all'),
	(76, 92, 3, 'jb_ods_merge_ps_mapping_eis', 'jb_ods_merge_ps_mapping_eis', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_ps_mapping_eis'),
	(77, 90, 3, 'jb_ods_merge_ps_mapping_nm01', 'jb_ods_merge_ps_mapping_nm01', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_ps_mapping_nm01'),
	(78, 65, 3, 'jb_ods_merge_eis_mdp1', 'jb_ods_merge_eis_mdp1', NULL, 11, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14', 'jb_ods_merge_eis_mdp1');
/*!40000 ALTER TABLE `task_run` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
