-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.2.6-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for control
CREATE DATABASE IF NOT EXISTS `control` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `control`;

-- Dumping structure for table control.task
CREATE TABLE IF NOT EXISTS `task` (
  `taskkey` int(11) NOT NULL AUTO_INCREMENT,
  `taskid` int(11) DEFAULT NULL,
  `taskgroupid` int(11) DEFAULT 1,
  `taskname` varchar(50) DEFAULT NULL,
  `taskbody` varchar(4000) DEFAULT NULL,
  `taskdescription` varchar(50) DEFAULT NULL,
  `tasktype` int(11) NOT NULL DEFAULT 11,
  `taskactiveflag` int(11) DEFAULT 0,
  `taskstatusflag` int(11) DEFAULT 0,
  `taskmodifieddate` datetime DEFAULT NULL,
  `taskcreationdate` datetime DEFAULT NULL,
  PRIMARY KEY (`taskkey`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;

-- Dumping data for table control.task: ~25 rows (approximately)
/*!40000 ALTER TABLE `task` DISABLE KEYS */;
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(1, 1, 1, 'truncate barrier_landing.ps_mapping_eis', 'truncate table barrier_landing.ps_mapping_eis;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(2, 2, 1, 'truncate barrier_landing.ps_mapping_nm01', 'truncate table barrier_landing.ps_mapping_nm01;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(3, 3, 1, 'truncate  barrier_landing.work_order_eis_map1', 'truncate table barrier_landing.work_order_eis_map1;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(4, 4, 2, 'truncate barrier_landing.work_order_eis_mcp1', 'truncate table barrier_landing.work_order_eis_mcp1;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(5, 5, 2, 'truncate barrier_landing.work_order_eis_mdp1', 'truncate table barrier_landing.work_order_eis_mdp1;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(6, 6, 1, 'truncate  barrier_landing.work_order_nm01_chis', 'truncate table barrier_landing.work_order_nm01_chis;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(7, 7, 1, 'truncate  barrier_landing.work_order_nm01_f3fa', 'truncate table barrier_landing.work_order_nm01_f3fa;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(8, 8, 1, 'truncate barrier_landing.work_order_nm01_grov', 'truncate table barrier_landing.work_order_nm01_grov;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(9, 9, 1, 'truncate barrier_landing.work_order_nm01_grow', 'truncate table barrier_landing.work_order_nm01_grow;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(10, 10, 1, 'truncate  barrier_landing.work_order_nm01_mj6a', 'truncate table barrier_landing.work_order_nm01_mj6a;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(11, 11, 1, 'truncate  barrier_landing.work_order_nm01_mkew', 'truncate table barrier_landing.work_order_nm01_mkew;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(12, 12, 1, 'truncate  barrier_landing.work_order_nm01_mst1', 'truncate table barrier_landing.work_order_nm01_mst1;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(13, 13, 1, 'truncate barrier_landing.work_order_nm01_stam', 'truncate table barrier_landing.work_order_nm01_stam;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(14, 14, 1, 'truncate  barrier_landing.work_order_nm01_wind', 'truncate table barrier_landing.work_order_nm01_wind;', NULL, 11, 1, 1, '2017-10-02 12:52:05', '2017-10-02 12:52:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(19, 19, 4, 'Load barrier_landing.work_order_eis_mcp1', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_eis_mcp1.txt\' REPLACE INTO TABLE `barrier_landing`.`work_order_eis_mcp1` CHARACTER SET latin1 FIELDS TERMINATED BY \'	\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`functional_loc`, `description`, `order_type`, `Order`, `maint_activ_type`, `description_4`, `planner_group`, `main_work_ctr`, `user_status`, `system_status`, `Priority`, `estimated_costs`, `total_act_costs`, `total_settlemt`, `total_plnnd_costs`, `tot_sum_plan`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `available_from30`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `subnet_work_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, country`, `device_data`, `sort_field`, `description_50`, `equipment`, `created_on`, `entered_by`, `billingform`, `actual_release`, `actual_finish`, `actual_finish1`, `basic_fin_date`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `bas_start_date`, `sched_start`, `actual_start1`, `start_time`, `sched_start_time`, `hist_fr`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_Area`, `cost_center`, `resp_cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_81`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority_95`, `wbs_element`, `wbs_ord_header`, `notification`, `region`, `revision`, `serial_number`, `material`, `service_product`, `service_product_104`, `division`, `division_sales` ,`location` , `street` ,`maint_plant` ,`telephone` ,`sales_office` ,`sales_group` ,`sales_org` ,`sales_org_sales` ,`superior_act` ,`distr_channel` ,`distr_channel_sal` ,`currency` ,`maint_item` ,`maintenance_plan` ,`plant` ,`comp` ,`overhead_key` ,`earlst_allow_fin_dat` ,`earl_allow_start_dat` ,`latest_allow_fin_dat` ,`original_due_date` ,`object_list` ,`catalog_type` ,`code_group` ,`coding`);', NULL, 12, 1, 1, '2017-10-02 14:55:27', '2017-10-02 14:55:27');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(20, 20, 4, 'Load barrier_landing.work_order_nm01_win', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_wind.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_wind` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`,`division_sales`,`location`,`street` ,`maint_plant` , `telephone` ,`estimated_costs` ,`sales_office` ,`sales_group` , `sales_org` ,`sales_org  - Sales` ,`superior_act` ,`distr_channel` ,`distr_Channel_sa_l` ,`currency` ,`maint_item` , `maintenance_plan` , `plant` , `comp` ,`overhead_key` ,`earlst_allow_fin_dat` , `earl_allow_start_dat` , `latest_allow_fin_dat` ,`original_due_date` ,`bas_start_date` ,`user_status` ,`system_status` ,`order_type` ,`revision` , `basic_fin_date` );', NULL, 12, 1, 1, '2017-10-02 15:04:50', '2017-10-02 15:04:50');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(21, 21, 4, 'Load barrier_landing.work_order_nm01_stam', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_stam.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_stam` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales`,`location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`, `currency`, `maint_item`,`maintenance_plan`,`plant`, `comp`,`overhead_key`,`earlst_allow_fin_dat`, `earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`, `user_status`,`system_status`,`order_type`, `revision`,`basic_fin_date`);', NULL, 12, 1, 1, '2017-10-02 15:04:55', '2017-10-02 15:04:55');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(22, 22, 4, 'Load barrier_landing.work_order_nm01_mst1', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_mst1.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_mst1` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales, `location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`,`user_status`,`system_status`,`order_type`,`revision`,`basic_fin_date`);\r\n', NULL, 12, 1, 1, '2017-10-02 15:04:57', '2017-10-02 15:04:57');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(23, 23, 4, 'Load barrier_landing.work_order_nm01_mkew', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_mkew.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_mkew` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales`,`location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`, `currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`,`user_status`,`system_status`,`order_type`,`revision`,`basic_fin_date`); ', NULL, 12, 1, 1, '2017-10-02 15:04:59', '2017-10-02 15:04:59');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(24, 24, 4, 'Load barrier_landing.work_order_nm01_mj6a', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_mj6a.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_mj6a` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales`, `location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`,`user_status`,`system_status`,`order_type`,`revision`,`basic_fin_date`);', NULL, 12, 1, 1, '2017-10-02 15:05:00', '2017-10-02 15:05:00');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(25, 25, 4, 'Load barrier_landing.work_order_nm01_grow', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_grow.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_grow` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`,`division`,`division_sales`,`location` ,`street` ,`maint_plant` ,`telephone` ,`estimated_costs` ,`sales_office` ,`sales_group` ,`sales_org` ,`sales_org  - Sales` ,`superior_act` ,`distr_channel` ,`distr_Channel_sa_l` ,`currency` ,`maint_item` ,`maintenance_plan` ,`plant` ,`comp` ,`overhead_key` ,`earlst_allow_fin_dat` ,`earl_allow_start_dat` ,`latest_allow_fin_dat` ,`original_due_date` ,`bas_start_date` , `user_status` ,`system_status` ,`order_type` ,`revision` ,`basic_fin_date`); ', NULL, 12, 1, 1, '2017-10-02 15:05:02', '2017-10-02 15:05:02');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(26, 26, 4, 'Load barrier_landing.work_order_nm01_grov', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_grov.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_grov` FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`, `division`, `division_sales`,`location`,`street`, `maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`, `original_due_date`,`bas_start_date`,`user_status`,`system_status`,`order_type`,`revision`,`basic_fin_date`);', NULL, 12, 1, 1, '2017-10-02 15:05:04', '2017-10-02 15:05:04');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(27, 27, 4, 'Load barrier_landing.work_order_nm01_f3fa', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_f3fa.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_f3fa` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `user_status`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`, `serial_number`, `material`, `service_product`, `service_product_1`,`division`,`division_sales`,`location`,`street`,`maint_plant`,`telephone`,`estimated_costs`,`sales_office`,`sales_group`,`sales_org`,`sales_org  - Sales`,`superior_act`,`distr_channel`,`distr_Channel_sa_l`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`bas_start_date`,`system_status`,`order_type`,`revision`,`basic_fin_date`);', NULL, 12, 1, 1, '2017-10-02 15:05:05', '2017-10-02 15:05:05');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(28, 28, 4, 'Load barrier_landing.work_order_nm01_chis', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_nm01_chis.csv\' REPLACE INTO TABLE `barrier_landing`.`work_order_nm01_chis` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`bas_start_date`, `order`, `functional_loc`, `description`, `description_1`, `planner_group`, `main_work_ctr`, `user_status`, `system_status`, `order_type`, `revision`, `basic_fin_date`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `Available_from_1`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `sub_network_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_2`, `equipment`, `created_on`, `entered_by`, `billing_form`, `actual_release`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `tot_sum_plan`, `actual_finish`, `actual_finish_1`, `total_settlemt`, `total_act_costs`, `total_plnnd_costs`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `sched_start`, `actual_start_1`, `start_time`, `sched_start_time`, `hist_fr`, `maint_activ_type`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_area`, `cost_center`, `resp _cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_3`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `object_list`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority`, `priority_1`, `wbs_element`, `wbs_ord_header`, `coding`, `code_group`, `catalog_type`, `notification`, `region`,`serial_number` ,`material` ,`service_product` ,`service_product_1` ,`division` ,`division_sales` ,`location` ,`street` ,`maint_plant` ,`telephone` ,`estimated_costs` ,`sales_office` ,`sales_group` ,`sales_org` ,`sales_org  - Sales` ,`superior_act` ,`distr_channel` ,`distr_Channel_sa_l` ,`currency` ,`maint_item` ,`maintenance_plan` ,`plant` ,`comp` ,`overhead_key` ,`earlst_allow_fin_dat`,`earl_allow_start_dat` ,`latest_allow_fin_dat` ,`original_due_date`);', NULL, 12, 1, 1, '2017-10-02 15:05:07', '2017-10-02 15:05:07');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(29, 29, 5, 'Load barrier_landing.work_order_eis_mdp1', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_eis_mdp1.txt\' REPLACE INTO TABLE `barrier_landing`.`work_order_eis_mdp1` CHARACTER SET latin1 FIELDS TERMINATED BY \'	\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`functional_loc`, `description`, `order_type`, `Order`, `maint_activ_type`, `description_4`, `planner_group`, `main_work_ctr`, `user_status`, `system_status`, `Priority`, `estimated_costs`, `total_act_costs`, `total_settlemt`, `total_plnnd_costs`, `tot_sum_plan`, `total_rev_act`, `tot_plan_rev`, `tot_sum_actual`, `abc_indic`, `reference_date`, `ref_element_pm_ps`, `address_number`, `reference_time`, `changed_on`, `changed_by`, `available_to`, `avail_to_time`, `asset`, `sub_number`, `available_from`, `available_from30`, `system_condition`, `work_center`, `priority_type`, `res_purc_req`, `subnet_work_of`, `order_category`, `plant_wk_cntr`, `assembly`, `assembly_desc`, `plant_section`, `acctg_indicator`, `po_date`, `po_number`, `company_code`, `city`, `district`, `country`, `device_data`, `sort_field`, `description_50`, `equipment`, `created_on`, `entered_by`, `billingform`, `actual_release`, `actual_finish`, `actual_finish1`, `basic_fin_date`, `sched_finish`, `basic_fin_time`, `finish_time`, `business_area`, `actual_start`, `bas_start_date`, `sched_start`, `actual_start1`, `start_time`, `sched_start_time`, `hist_fr`, `planning_plant`, `costing_sheet`, `sales_document`, `item`, `co_Area`, `cost_center`, `resp_cost_cntr`, `customer`, `leading_order`, `deletion_flag`, `long_txt_exists`, `description_81`, `superior_order`, `base_unit`, `quantity`, `room`, `list_name`, `object_number`, `paging_status`, `pgrp_task_list`, `order_plan_ind`, `group_counter`, `group`, `postal_code`, `profit_center`, `priority_95`, `wbs_element`, `wbs_ord_header`, `notification`, `region`, `revision`, `serial_number`, `material`, `service_product`, `service_product_104`, `division`, `division_sales`,`location`,`street`,`maint_plant`,`telephone`,`sales_office`,`sales_group`,`sales_org`,`sales_org_sales`,`superior_act`,`distr_channel`,`distr_channel_sal`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`object_list`,`catalog_type`,`code_group`,`coding`);\r\n', NULL, 12, 1, 1, '2017-10-02 15:05:08', '2017-10-02 15:05:08');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(30, 30, 5, 'Load barrier_landing.work_order_eis_map1', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'work_order_eis_map1.txt\' REPLACE INTO TABLE `barrier_landing`.`work_order_eis_map1` CHARACTER SET latin1 FIELDS TERMINATED BY \'	\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES ( `functional_loc`,`description`,`order_type`,`Order`,`maint_activ_type`,`description_4`,`planner_group`,`main_work_ctr`,`user_status`,`system_status`,`Priority`,`estimated_costs`,`total_act_costs`,`total_settlemt`,`total_plnnd_costs`,`tot_sum_plan`,`total_rev_act`,`tot_plan_rev`,`tot_sum_actual`,`abc_indic`,`reference_date`,`ref_element_pm_ps`,`address_number`,`reference_time`,`changed_on`,`changed_by`,`available_to`,`avail_to_time`,`asset`,`sub_number`,`available_from`,`available_from30`,`system_condition`,`work_center`,`priority_type`,`res_purc_req`,`subnet_work_of`,`order_category`,`plant_wk_cntr`,`assembly`,`assembly_desc`,`plant_section`,`acctg_indicator`,`po_date`,`po_number`,`company_code`,`city`,`district`,`country`,`device_data`,`sort_field`,`description_50`,`equipment`,`created_on`,`entered_by`,`billingform`,`actual_release`,`actual_finish`,`actual_finish1`,`basic_fin_date`,`sched_finish`,`basic_fin_time`,`finish_time`,`business_area`,`actual_start`,`bas_start_date`,`sched_start`,`actual_start1`,`start_time`,`sched_start_time`,`hist_fr`,`planning_plant`,`costing_sheet`,`sales_document`,`item`,`co_Area`,`cost_center`,`resp_cost_cntr`,`customer`,`leading_order`,`deletion_flag`,`long_txt_exists`,`description_81`,`superior_order`,`base_unit`,`quantity`,`room`,`list_name`,`object_number`,`paging_status`,`pgrp_task_list`,`order_plan_ind`,`group_counter`,`group`,`postal_code`,`profit_center`,`priority_95`,`wbs_element`,`wbs_ord_header`,`notification`,`region`,`revision`,`serial_number`,`material`,`service_product`,`service_product_104`,`division`,`division_sales`,`location`,`street`,`maint_plant`,`telephone`,`sales_office`,`sales_group`,`sales_org`,`sales_org_sales`,`superior_act`,`distr_channel`,`distr_channel_sal`,`currency`,`maint_item`,`maintenance_plan`,`plant`,`comp`,`overhead_key`,`earlst_allow_fin_dat`,`earl_allow_start_dat`,`latest_allow_fin_dat`,`original_due_date`,`object_list`,`catalog_type`,`code_group`,`coding`);', NULL, 12, 1, 1, '2017-10-02 15:05:10', '2017-10-02 15:05:10');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(31, 31, 4, 'Load barrier_landing.ps_mapping_nm01', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'ps_mapping_nm01.csv\' REPLACE INTO TABLE `barrier_landing`.`ps_mapping_nm01` CHARACTER SET latin1 FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`floc`, `floc_type`, `description`, `support_floc`, `support_floc_description`, `abc_indicator`, `criticality_justification`, `ps_ref1`, `ps_ref2`, `new_ps_ref_1`, `new_ps_ref_2`, `nl_sce`);', NULL, 12, 1, 1, '2017-10-02 15:05:12', '2017-10-02 15:05:12');
INSERT INTO `task` (`taskkey`, `taskid`, `taskgroupid`, `taskname`, `taskbody`, `taskdescription`, `tasktype`, `taskactiveflag`, `taskstatusflag`, `taskmodifieddate`, `taskcreationdate`) VALUES
	(32, 32, 5, 'Load barrier_landing.ps_mapping_eis', 'LOAD DATA LOW_PRIORITY LOCAL INFILE \'ps_mapping_eis.csv\' REPLACE INTO TABLE `barrier_landing`.`ps_mapping_eis` FIELDS TERMINATED BY \',\' OPTIONALLY ENCLOSED BY \'"\' ESCAPED BY \'"\' LINES TERMINATED BY \'\\r\\n\' IGNORE 1 LINES (`floc`, `description`, `system_status`, `user_status`, `support_floc`, `ps_ref_1`, `ps_ref_2`, `ps_ref_3`, `ps_mapping_barrier_1`, `ps_mapping_barrier_2`, `ps_mapping_barrier_3`);', NULL, 12, 1, 1, '2017-10-02 15:05:14', '2017-10-02 15:05:14');
/*!40000 ALTER TABLE `task` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
